### ISSUE TITLE
augmentation random sampling 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by ummjevel** [siwooyong/LG-AI-Challenge-for-Plant-Classification#1]
안녕하세요.
먼저는 멋진 코드를 공유해주셔서 감사합니다.

제가 이해한 게 맞는지 궁금하기도 하고, README와 코드 상에 차이가 있는 것 같아서 문의드립니다.

Preprocessing(sequence) 부분에서
Augmentations : 만약 길이가 500이상이라면 random으로 sampling(2씩) 
이라고 적어주셨는데,
CustomDataset 클래스에 보면 
estiTime1==estiTime2 and len(df)>400
이런 식으로 400 이라는 숫자가 있습니다.
혹시 오타가 맞을까요?
400이 맞는 것인지, 500이 맞는 것인지 궁금합니다!

답장 기다리겠습니다.
감사합니다.

**Comment by siwooyong** [comment]
답변이 늦어서 죄송합니다!

말씀하신대로 오타입니다! 400이 맞습니다!

좋은 질문 감사합니다.

**Comment by ummjevel** [comment]
넵 답변 감사합니다!

**Comment by ummjevel** [comment]
답변 감사합니다! 혹시 다른 대회 참여자들과는 다르게 400개로만 줄이신 이유를 알 수 있을까요?
어떻게 생각해내신 건지도 궁금합니다!

**Comment by ummjevel** [comment]
답변 감사합니다! 혹시 다른 대회 참여자들과는 다르게 400개로만 줄이신 이유를 알 수 있을까요?
어떻게 생각해내신 건지도 궁금합니다!

**Comment by siwooyong** [comment]
이미지 데이터에 CutMix를 적용하여 성능을 향상하고 있는 상황에서 시퀀스 데이터에도 Augmentation 효과를 부여하고자 했습니다. 시퀀스 데이터는 연속 데이터이기 때문에 특정 주기로 샘플링을 수행해도 데이터에 큰 손상이 가해지지 않을 것으로 판단했습니다. 그래서 주기를 2, 3, 4 등으로 변화시켜 실험을 진행해보았고, 주기가 2일 때 가장 좋은 성능을 얻었습니다. 이어서 시퀀스 데이터에 대한 Augmentation을 적용할 때, 원래는 길이가 500 이상일 때만 적용했었는데, 더 많은 데이터에 Augmentation 효과를 주기 위해 길이가 400 이상인 데이터에 대해서도 시도해보았습니다. 실제로 성능 향상이 더 크게 나타났기 때문에 해당 값으로 최종 설정하였습니다.

좋은 질문 감사합니다!

**Comment by ummjevel** [comment]
친절한 답변 감사합니다!!
